<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BodyCamAI.Api</RootNamespace>
    <AssemblyName>BodyCamAI.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BodyCamAI.Application\BodyCamAI.Application.csproj" />
    <ProjectReference Include="..\BodyCamAI.Infrastructure\BodyCamAI.Infrastructure.csproj" />
    <ProjectReference Include="..\BodyCamAI.Shared\BodyCamAI.Shared.csproj" />
  </ItemGroup>

</Project>
