// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PERA360.Infrastructure.Persistence;

#nullable disable

namespace PERA360.Infrastructure.Migrations
{
    [DbContext(typeof(BodycamDbContext))]
    partial class BodycamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PERA360.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AggressivePostureDetected")
                        .HasColumnType("bit");

                    b.Property<double?>("Agitation")
                        .HasColumnType("float");

                    b.Property<string>("AiAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AvgEnergy")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPitchHz")
                        .HasColumnType("float");

                    b.Property<double?>("BaselinePitchHz")
                        .HasColumnType("float");

                    b.Property<bool?>("BriberyVisualDetected")
                        .HasColumnType("bit");

                    b.Property<bool?>("ConcealedGesturesDetected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerSegmentsCount")
                        .HasColumnType("int");

                    b.Property<double?>("CustomerTotalSec")
                        .HasColumnType("float");

                    b.Property<string>("DominantEmotion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("EmotionAgitation")
                        .HasColumnType("int");

                    b.Property<int>("EmotionAnger")
                        .HasColumnType("int");

                    b.Property<int>("EmotionCalm")
                        .HasColumnType("int");

                    b.Property<int>("EmotionContempt")
                        .HasColumnType("int");

                    b.Property<int>("EmotionFear")
                        .HasColumnType("int");

                    b.Property<int>("EmotionFrustration")
                        .HasColumnType("int");

                    b.Property<int>("EmotionIntimidation")
                        .HasColumnType("int");

                    b.Property<string>("EmotionNarrative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmotionNeutral")
                        .HasColumnType("int");

                    b.Property<bool>("EoDetected")
                        .HasColumnType("bit");

                    b.Property<int?>("EoSegmentsCount")
                        .HasColumnType("int");

                    b.Property<double>("EoSimilarity")
                        .HasColumnType("float");

                    b.Property<double?>("EoTotalSec")
                        .HasColumnType("float");

                    b.Property<string>("ExtractedName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExtractedStation")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("GreetingCompliance")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("GreetingScore")
                        .HasColumnType("int");

                    b.Property<int>("HighCount")
                        .HasColumnType("int");

                    b.Property<int>("KwScore")
                        .HasColumnType("int");

                    b.Property<double?>("LoudDurationSec")
                        .HasColumnType("float");

                    b.Property<string>("MatchedOfficerId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("MediumCount")
                        .HasColumnType("int");

                    b.Property<bool?>("NameIntroduced")
                        .HasColumnType("bit");

                    b.Property<bool?>("PhysicalContactDetected")
                        .HasColumnType("bit");

                    b.Property<double?>("PitchRatio")
                        .HasColumnType("float");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("RoleMentioned")
                        .HasColumnType("bit");

                    b.Property<bool?>("SalamFound")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("SpeakerCount")
                        .HasColumnType("int");

                    b.Property<bool?>("StationMentioned")
                        .HasColumnType("bit");

                    b.Property<string>("ToneLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TonePercentAngry")
                        .HasColumnType("int");

                    b.Property<int?>("TonePercentBribe")
                        .HasColumnType("int");

                    b.Property<int?>("TonePercentHarsh")
                        .HasColumnType("int");

                    b.Property<int?>("TonePercentNormal")
                        .HasColumnType("int");

                    b.Property<int>("ToneScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<string>("TranscriptEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranscriptUrdu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranscriptionMethod")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VisualAnalysisStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VisualAnalysisStatusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisualRiskScore")
                        .HasColumnType("int");

                    b.Property<string>("VisualSummary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.HasIndex("TotalScore");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Officer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Area")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enrolled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoiceprintPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Badge")
                        .IsUnique();

                    b.ToTable("officers", (string)null);
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Recording", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("OfficerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MediaType");

                    b.HasIndex("OfficerId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("recordings", (string)null);
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Violation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ImpactPercent")
                        .HasColumnType("float");

                    b.Property<string>("KeywordsFound")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SeverityIndex")
                        .HasColumnType("int");

                    b.Property<string>("SeverityLabel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.ToTable("violations", (string)null);
                });

            modelBuilder.Entity("PERA360.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("PERA360.Domain.Entities.Recording", "Recording")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("PERA360.Domain.Entities.AnalysisResult", "RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Recording", b =>
                {
                    b.HasOne("PERA360.Domain.Entities.Officer", "Officer")
                        .WithMany("Recordings")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Violation", b =>
                {
                    b.HasOne("PERA360.Domain.Entities.Recording", "Recording")
                        .WithMany("Violations")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Officer", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("PERA360.Domain.Entities.Recording", b =>
                {
                    b.Navigation("AnalysisResult");

                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
