<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PERA360.Shared</RootNamespace>
    <AssemblyName>PERA360.Shared</AssemblyName>
  </PropertyGroup>

</Project>
